#java -jar hello-spring-cloud-web-admin-feign-1.0.0-SNAPSHOT.jar --spring.profiles.active=test
# 指明启动test环境 激活对应的配置文件
spring:
  cloud:
    config:
      uri: http://localhost:8888
      #配置文件的名字
      name: web-admin-feign
      label: master
      profile: test
